### ISSUE TITLE
Question: QueueTrigger

### ISSUE THREAD

**Issue by mohsinonxrm** [jongeorge1/azure-functions-docker-hello-world-demo#1]
@jongeorge1 , First of all, I really liked the blog post, so much that I wanted to experiment myself and ordered Raspberry Pi 4 B.
I was able to follow your blog post and was able to run the hello world azure function.

However, I was trying to create a QueueTrigger Azure Function and tried to follow pretty much the same steps, however, it isn't working, no errors, nothing. Messages stay in the queue.
I've provided the storage account connection string in the ENV variables but still nothing.

Can you please point out what I am doing wrong?

Dockerfile
`FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS installer-env

COPY . /src/dotnet-function-app
RUN cd /src/dotnet-function-app && \
    mkdir -p /home/site/wwwroot && \
    dotnet publish *.csproj --output /home/site/wwwroot

FROM mcr.microsoft.com/azure-functions/dotnet:2.0-arm32v7
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY --from=installer-env ["/home/site/wwwroot", "/home/site/wwwroot"]`

host.json:
`{
  "version": "2.0",
  "extensions": {
    "queues": {
      "maxPollingInterval": "00:00:02",
      "visibilityTimeout": "00:00:30",
      "batchSize": 16,
      "maxDequeueCount": 5,
      "newBatchThreshold": 8
    }
  }
}`

queuetrigger.cs
`public static class queuetrigger
    {
        [FunctionName("queuetrigger")]
        public static void Run([QueueTrigger("myqueue-items", Connection = "")]string myQueueItem, ILogger log)
        {
            log.LogInformation($"C# Queue trigger function processed: {myQueueItem}");
        }
    }`

**Comment by jongeorge1** [comment]
Hi. Glad you enjoyed the post. In your QueueTrigger attribute, doesn't the Connection property need to contain the name of the app setting that contains the connection string? Or does it default to some known value?

If that's not the problem then it's not obvious to me from the above. If you can push the code to a public repo you can point me at I'll take a look and see if I can get it working.

**Comment by mohsinonxrm** [comment]
@jongeorge1 , from what I understand, if the connection property is left blank it uses the default "AzureWebJobsStorage", which I did in the docker file as an ENV. I also provided it explicitly but it just doesn't work.

I've tried to use the function core tools/CLI on the Raspberry Pi 4B itself as well but there's another issue with that.

I'm just trying to make an QueueTrigger Azure Function work in Docker on Raspberry PI 4B.

I'll post what I have on github and share it with you.

Thanks again for getting back to me, really appreciate it.

**Comment by mohsinonxrm** [comment]
@jongeorge1 , so I played with it a bit more and nothing worked. I've uploaded the source to GitHub at:
https://github.com/mohsinonxrm/azqueuetrigger/tree/master/queuetrigger/queuetrigger

Please make sure to update the storage account connection string for AzureWebJobsStorage in the Dockerfile and also in the local.settings.json before testing or building the image.

Here's the output I'm getting when I run the docker image.
`Hosting environment: Production
Content root path: /
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.`

and nothing happens. all messages stay in the queue, not sure how to debug this either.

**Comment by mohsinonxrm** [comment]
@jongeorge1 , did you get a chance to take a look at this?

**Comment by jongeorge1** [comment]
Hi @mohsinonxrm, apologies for the huge delay, things have been a bit hectic lately.

I've just pulled your code and run it on my Pi - once I'd removed `--publish linux-arm` from the `Dockerfile` and added my `AzureWebJobsStorage` connection string, it built and ran with no issues, consuming messages off the queue. Did you manage to fix the problem yourself?

```info: Host.Startup[0]
      Found the following functions:
      queuetrigger.QueueTrigger.Run

info: Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostHttpRoutesManager[0]
      Initializing function HTTP routes
      No HTTP routes mapped

info: Host.Startup[412]
      Host initialized (909ms)
info: Host.Startup[413]
      Host started (955ms)
info: Host.Startup[0]
      Job host started
Hosting environment: Production
Content root path: /
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
info: Host.General[316]
      Host lock lease acquired by instance ID '00000000000000000000000032701C8A'.
info: Function.queuetrigger[0]
      Executing 'queuetrigger' (Reason='New queue message detected on 'myqueue-items'.', Id=7d5e0c9a-2d29-4b47-8874-172c95777223)
info: Function.queuetrigger[0]
      Trigger Details: MessageId: fa3295ab-b26d-4641-a0f1-ac46893094ce, DequeueCount: 1, InsertionTime: 11/25/2019 12:50:03 +00:00
info: Function.queuetrigger.User[0]
      C# Queue trigger function processed: hello
info: Function.queuetrigger[0]
      Executed 'queuetrigger' (Succeeded, Id=7d5e0c9a-2d29-4b47-8874-172c95777223)
info: Function.queuetrigger[0]
      Executing 'queuetrigger' (Reason='New queue message detected on 'myqueue-items'.', Id=103d32f0-9a7d-4c70-a2c4-dcaa61a578c4)
info: Function.queuetrigger[0]
      Trigger Details: MessageId: 537e3f00-10ae-4c51-b1b6-4ed214af4514, DequeueCount: 1, InsertionTime: 11/25/2019 12:52:59 +00:00
info: Function.queuetrigger.User[0]
      C# Queue trigger function processed: world
info: Function.queuetrigger[0]
      Executed 'queuetrigger' (Succeeded, Id=103d32f0-9a7d-4c70-a2c4-dcaa61a578c4)```

**Comment by mohsinonxrm** [comment]
@jongeorge1 , my apologies for the delay in getting back to you. Yes, I was able to resolve the issue. I couldn't get back to you last year as I was traveling and then I forgot about it.

Thanks again for your awesome article and help with this.
